name: Django CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  POSTGRES_DB: football_transfermarkt
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/football_transfermarkt
  DJANGO_SETTINGS_MODULE: football_transfermarkt.settings

jobs:
  ruff:
    name: Run Ruff Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: football_transfermarkt
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser -d football_transfermarkt"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to start
        run: |
          echo "Waiting for PostgreSQL..."
          sleep 10

      - name: Debug check PostgreSQL logs
        run: docker logs $(docker ps -q --filter "ancestor=postgres:15") || true

      - name: Run migrations
        run: |
          source venv/bin/activate
          cd football_transfermarkt
          python manage.py migrate

      - name: Run Tests
        run: |
          source venv/bin/activate
          cd football_transfermarkt
          python manage.py test

  build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/django-app:latest ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }}

  deploy:
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/django-app:latest

            echo "Stopping old container..."
            sudo docker stop django-app || true
            sudo docker rm django-app || true

            echo "Running new container..."
            sudo docker run -d --name django-app -p 9000:9000 \
              --env-file /home/${{ secrets.SERVER_USER }}/.env \
              ${{ secrets.DOCKER_USERNAME }}/django-app:latest

            echo "Restarting Gunicorn"
            sudo systemctl restart gunicorn || true

            echo "Deployment complete!"
