name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/django-app:latest

            echo "Stopping old container..."
            sudo docker stop django-app || true
            sudo docker rm django-app || true

            echo "Running new container..."
            sudo docker run -d --name django-app -p 9000:9000 \
              --env-file /home/${{ secrets.SERVER_USER }}/.env \
              ${{ secrets.DOCKER_USERNAME }}/django-app:latest

            echo "Restarting Gunicorn"
            sudo systemctl restart gunicorn || true

            echo "Deployment complete!"
