name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            👋 Hi there! Thank you for opening your first issue in this repository.
            We really appreciate your contribution! A maintainer will review it soon.
            Feel free to provide any additional context or screenshots if needed.
          
          pr-message: >
            🎉 Thanks for submitting your first pull request!  
            We appreciate your effort and time. A maintainer will review it shortly.  
            If you haven’t already, please make sure your PR includes relevant tests, follows the contribution guidelines, and passes all checks.
